language: go

dist: bionic

go:
  - 1.13.x
  - master

arch:
  - amd64

os:
  - linux

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/vaultsync
  - cd $HOME/src/vaultsync
  - go get github.com/magefile/mage

script:
  - go mod download || true
  - mage -v test
  - go test -tags=CI -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
