language: go

dist: bionic

git:
  depth: 1

go:
  - 1.13.x
  - master

arch:
  - amd64

os:
  - linux

install: true

script:
  - go run mage.go -v test
  - go test -tags=CI -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
