apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: vaultsync
        image: thatinfrastructureguy/vaultsync:v0.0.14
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: provider-credentials
        env:
        - name: PROVIDER
          value: "azure"
        - name: REFRESH_RATE
          value: "0"
        - name: VAULT_NAME
          value: "my-secrets-manager"
        - name: SECRET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONVERT_HYPHENS_TO_UNDERSCORES
          value: "true" 
      containers:
      - envFrom:
        - secretRef:
            name: "my-secrets-manager"
        name: nginxapp
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
