# Copyright 2020 Kulkarni, Ashish <thatInfrastructureGuy@gmail.com>
# Author: Ashish Kulkarni
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: vaultsync
        image: thatinfrastructureguy/vaultsync:v0.0.14
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: provider-credentials
        env:
        - name: PROVIDER
          value: "azure"
        - name: REFRESH_RATE
          value: "0"
        - name: VAULT_NAME
          value: "my-secrets-manager"
        - name: SECRET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONVERT_HYPHENS_TO_UNDERSCORES
          value: "true" 
      containers:
      - envFrom:
        - secretRef:
            name: "my-secrets-manager"
        name: nginxapp
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
