apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: vaultsync
        image: datinfraguy/vaultsync:v0.0.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: vaultsync
        env:
        - name: KVAULT
          value: kvtestin
        - name: SECRETS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONVERT_HYPHENS_TO_UNDERSCORES
          value: "true" 
      containers:
      - envFrom:
        - secretRef:
            name: kvtestin
        name: nginxapp
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
